all:
	g++ -o np_single_proc np_single_proc_server.cpp npShell_single_proc.cpp npShell_single_proc.h np_single_proc_server.h
	gcc -o np_simple np_simple_server.c npShell.c npShell.h
clean:
	rm np_single_proc
	rm np_simple
